// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhz5qzkPnp63MF_Tb3Y2qt0Ff94UY7g2U',
    appId: '1:947222283851:web:dd6ecf9c739be78e15efce',
    messagingSenderId: '947222283851',
    projectId: 'student-management-a98a4',
    authDomain: 'student-management-a98a4.firebaseapp.com',
    storageBucket: 'student-management-a98a4.appspot.com',
    measurementId: 'G-ZCDN8M90KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgeyRMvir_96eqkVr6pAGhcWJP9mKsy4',
    appId: '1:947222283851:android:6586d047d12cbb8115efce',
    messagingSenderId: '947222283851',
    projectId: 'student-management-a98a4',
    storageBucket: 'student-management-a98a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATyD7DIxYLDHYYHjBkIp3AU4YHxhCl994',
    appId: '1:947222283851:ios:1e490304a44d946015efce',
    messagingSenderId: '947222283851',
    projectId: 'student-management-a98a4',
    storageBucket: 'student-management-a98a4.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATyD7DIxYLDHYYHjBkIp3AU4YHxhCl994',
    appId: '1:947222283851:ios:1e490304a44d946015efce',
    messagingSenderId: '947222283851',
    projectId: 'student-management-a98a4',
    storageBucket: 'student-management-a98a4.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhz5qzkPnp63MF_Tb3Y2qt0Ff94UY7g2U',
    appId: '1:947222283851:web:f0aa3802cd0ae8db15efce',
    messagingSenderId: '947222283851',
    projectId: 'student-management-a98a4',
    authDomain: 'student-management-a98a4.firebaseapp.com',
    storageBucket: 'student-management-a98a4.appspot.com',
    measurementId: 'G-J7NE3WHBWK',
  );
}
